name: CI-GitHubActions
env:
   APPLICATION_NAME    : "My_Flask"
   PACKAGE_NAME        : "flask-deploy-ver: ${{ github.sha }}"

on:
   push:
     branches: 
        - main


jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello msg
      run: echo "Hello world from Testing Job"
      
    - name: Execure few commands
      run: | 
       echo "Hello Krtkh"
       echo "Hello Evgenii"
       echo "Application name: ${{ env.APPLICATION_NAME }}"
    
    
    - name: Git clone  my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
    - name: msg
      run: cat /README.md

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello msg
      run: echo "Hello world from Deploy Job"
      
    - name: Print package name
      run: echo "Deploy package name ${{ env.PACKAGE_NAME }}"
      
    - name: Lets test some packages if they are here 1
      run: python --version

    - name: Lets test some packages if they are here 2
      run: zip
