name: CI-GitHubActions
env:
   APPLICATION_NAME: "My_Flask"
   PACKAGE_NAME: "flask-deploy-ver: ${{ github.sha }}"

on:
   push:
     branches: 
        - main


jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello msg
      run: echo "Hello world from Testing Job"
           
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello msg
      run: echo "Hello world from Deploy Job"
